#!/usr/bin/env bash
# shellcheck source=/dev/null
#
# A light wieght multipurpose file organiser built in bash
# 
#

set -euo pipefail

readonly VERSION=0.0.1
readonly PROG_NAME=$(basename "$0")


export DATE="$(date +%Y_%m_%d)"
export SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
export LOGS_DIR=${LOGS_DIR:-"$HOME/.local/state/$PROG_NAME/logs"}
export BACKUP_DIR=${BACKUP_DIR:-"$HOME/.local/share/$PROG_NAME/"}

export core_dir="$SCRIPT_DIR/lib/core"
export function_dir="$SCRIPT_DIR/lib/functions"




main() {
    printf "Enter the directory to organise (ENTER /bye to quit): "
}

main
